# CMakeLists head

cmake_policy(SET CMP0079 NEW)

file(GLOB BUSYBOX_SOURCES
    ${BUSYBOX_PATH}/raw/archival/libarchive/open_transformer.c
    ${BUSYBOX_PATH}/raw/archival/libarchive/init_handle.c
    ${BUSYBOX_PATH}/raw/archival/libarchive/filter_accept_all.c
    ${BUSYBOX_PATH}/raw/archival/libarchive/filter_accept_list.c
    ${BUSYBOX_PATH}/raw/archival/libarchive/filter_accept_list_reassign.c
    ${BUSYBOX_PATH}/raw/archival/libarchive/unpack_ar_archive.c
    ${BUSYBOX_PATH}/raw/archival/libarchive/data_extract_all.c
    ${BUSYBOX_PATH}/raw/archival/libarchive/find_list_entry.c
    ${BUSYBOX_PATH}/raw/archival/libarchive/data_align.c
    ${BUSYBOX_PATH}/raw/archival/libarchive/data_skip.c
    ${BUSYBOX_PATH}/raw/archival/libarchive/unsafe_prefix.c
    ${BUSYBOX_PATH}/raw/archival/libarchive/unsafe_symlink_target.c
    ${BUSYBOX_PATH}/raw/archival/libarchive/get_header_ar.c
    ${BUSYBOX_PATH}/raw/archival/libarchive/get_header_tar.c
    ${BUSYBOX_PATH}/raw/archival/libarchive/get_header_tar_gz.c
    ${BUSYBOX_PATH}/raw/archival/libarchive/header_skip.c
    ${BUSYBOX_PATH}/raw/archival/libarchive/seek_by_jump.c
    ${BUSYBOX_PATH}/raw/archival/libarchive/seek_by_read.c
    ${BUSYBOX_PATH}/raw/archival/libarchive/decompress_bunzip2.c
    ${BUSYBOX_PATH}/raw/archival/libarchive/decompress_gunzip.c
    ${BUSYBOX_PATH}/raw/archival/bbunzip.c
    ${BUSYBOX_PATH}/raw/archival/dpkg.c

    ${BUSYBOX_PATH}/raw/console-tools/chvt.c
    ${BUSYBOX_PATH}/raw/console-tools/clear.c
    ${BUSYBOX_PATH}/raw/console-tools/deallocvt.c
    ${BUSYBOX_PATH}/raw/console-tools/dumpkmap.c
    ${BUSYBOX_PATH}/raw/console-tools/fgconsole.c
    ${BUSYBOX_PATH}/raw/console-tools/kbd_mode.c
    ${BUSYBOX_PATH}/raw/console-tools/loadkmap.c
    ${BUSYBOX_PATH}/raw/console-tools/reset.c
    ${BUSYBOX_PATH}/raw/console-tools/setkeycodes.c
    ${BUSYBOX_PATH}/raw/console-tools/showkey.c

    ${BUSYBOX_PATH}/raw/coreutils/libcoreutils/cp_mv_stat.c
    ${BUSYBOX_PATH}/raw/coreutils/libcoreutils/getopt_mk_fifo_nod.c
    ${BUSYBOX_PATH}/raw/coreutils/basename.c
    ${BUSYBOX_PATH}/raw/coreutils/cat.c
    ${BUSYBOX_PATH}/raw/coreutils/chgrp.c
    ${BUSYBOX_PATH}/raw/coreutils/chmod.c
    ${BUSYBOX_PATH}/raw/coreutils/chown.c
    ${BUSYBOX_PATH}/raw/coreutils/chroot.c
    ${BUSYBOX_PATH}/raw/coreutils/cksum.c
    ${BUSYBOX_PATH}/raw/coreutils/comm.c
    ${BUSYBOX_PATH}/raw/coreutils/cp.c
    ${BUSYBOX_PATH}/raw/coreutils/cut.c
    ${BUSYBOX_PATH}/raw/coreutils/date.c
    ${BUSYBOX_PATH}/raw/coreutils/dd.c
    ${BUSYBOX_PATH}/raw/coreutils/df.c
    ${BUSYBOX_PATH}/raw/coreutils/dirname.c
    ${BUSYBOX_PATH}/raw/coreutils/dos2unix.c
    ${BUSYBOX_PATH}/raw/coreutils/du.c
    ${BUSYBOX_PATH}/raw/coreutils/echo.c
    ${BUSYBOX_PATH}/raw/coreutils/env.c
    ${BUSYBOX_PATH}/raw/coreutils/expand.c
    ${BUSYBOX_PATH}/raw/coreutils/expr.c
    ${BUSYBOX_PATH}/raw/coreutils/factor.c
    ${BUSYBOX_PATH}/raw/coreutils/false.c
    ${BUSYBOX_PATH}/raw/coreutils/fold.c
    ${BUSYBOX_PATH}/raw/coreutils/head.c
    ${BUSYBOX_PATH}/raw/coreutils/hostid.c
    ${BUSYBOX_PATH}/raw/coreutils/install.c
    ${BUSYBOX_PATH}/raw/coreutils/link.c
    ${BUSYBOX_PATH}/raw/coreutils/ln.c
    ${BUSYBOX_PATH}/raw/coreutils/logname.c
    ${BUSYBOX_PATH}/raw/coreutils/ls.c
    ${BUSYBOX_PATH}/raw/coreutils/md5_sha1_sum.c
    ${BUSYBOX_PATH}/raw/coreutils/mkdir.c
    ${BUSYBOX_PATH}/raw/coreutils/mkfifo.c
    ${BUSYBOX_PATH}/raw/coreutils/mknod.c
    ${BUSYBOX_PATH}/raw/coreutils/mktemp.c
    ${BUSYBOX_PATH}/raw/coreutils/mv.c
    ${BUSYBOX_PATH}/raw/coreutils/nl.c
    ${BUSYBOX_PATH}/raw/coreutils/nohup.c
    ${BUSYBOX_PATH}/raw/coreutils/od.c
    ${BUSYBOX_PATH}/raw/coreutils/paste.c
    ${BUSYBOX_PATH}/raw/coreutils/printenv.c
    ${BUSYBOX_PATH}/raw/coreutils/printf.c
    ${BUSYBOX_PATH}/raw/coreutils/pwd.c
    ${BUSYBOX_PATH}/raw/coreutils/readlink.c
    ${BUSYBOX_PATH}/raw/coreutils/realpath.c
    ${BUSYBOX_PATH}/raw/coreutils/rm.c
    ${BUSYBOX_PATH}/raw/coreutils/rmdir.c
    ${BUSYBOX_PATH}/raw/coreutils/seq.c
    ${BUSYBOX_PATH}/raw/coreutils/shred.c
    ${BUSYBOX_PATH}/raw/coreutils/shuf.c
    ${BUSYBOX_PATH}/raw/coreutils/sleep.c
    ${BUSYBOX_PATH}/raw/coreutils/sort.c
    ${BUSYBOX_PATH}/raw/coreutils/split.c
    ${BUSYBOX_PATH}/raw/coreutils/stat.c
    ${BUSYBOX_PATH}/raw/coreutils/stty.c
    ${BUSYBOX_PATH}/raw/coreutils/sum.c
    ${BUSYBOX_PATH}/raw/coreutils/sync.c
    ${BUSYBOX_PATH}/raw/coreutils/tac.c
    ${BUSYBOX_PATH}/raw/coreutils/tail.c
    ${BUSYBOX_PATH}/raw/coreutils/tee.c
    ${BUSYBOX_PATH}/raw/coreutils/test.c
    ${BUSYBOX_PATH}/raw/coreutils/test_ptr_hack.c
    ${BUSYBOX_PATH}/raw/coreutils/timeout.c
    ${BUSYBOX_PATH}/raw/coreutils/touch.c
    ${BUSYBOX_PATH}/raw/coreutils/tr.c
    ${BUSYBOX_PATH}/raw/coreutils/true.c
    ${BUSYBOX_PATH}/raw/coreutils/truncate.c
    ${BUSYBOX_PATH}/raw/coreutils/tsort.c
    ${BUSYBOX_PATH}/raw/coreutils/tty.c
    ${BUSYBOX_PATH}/raw/coreutils/uname.c
    ${BUSYBOX_PATH}/raw/coreutils/uniq.c
    ${BUSYBOX_PATH}/raw/coreutils/unlink.c
    ${BUSYBOX_PATH}/raw/coreutils/usleep.c
    ${BUSYBOX_PATH}/raw/coreutils/uudecode.c
    ${BUSYBOX_PATH}/raw/coreutils/uuencode.c
    ${BUSYBOX_PATH}/raw/coreutils/wc.c
    ${BUSYBOX_PATH}/raw/coreutils/whoami.c
    ${BUSYBOX_PATH}/raw/coreutils/yes.c

    ${BUSYBOX_PATH}/raw/debianutils/which.c

    ${BUSYBOX_PATH}/raw/editors/awk.c
    ${BUSYBOX_PATH}/raw/editors/cmp.c
    ${BUSYBOX_PATH}/raw/editors/diff.c
    ${BUSYBOX_PATH}/raw/editors/ed.c
    ${BUSYBOX_PATH}/raw/editors/patch.c
    ${BUSYBOX_PATH}/raw/editors/sed.c
    ${BUSYBOX_PATH}/raw/editors/vi.c

    ${BUSYBOX_PATH}/raw/findutils/find.c
    ${BUSYBOX_PATH}/raw/findutils/grep.c
    ${BUSYBOX_PATH}/raw/findutils/xargs.c

    ${BUSYBOX_PATH}/raw/init/bootchartd.c
    ${BUSYBOX_PATH}/raw/init/halt.c
    ${BUSYBOX_PATH}/raw/init/init.c

    ${BUSYBOX_PATH}/raw/libpwdgrp/uidgid_get.c

    ${BUSYBOX_PATH}/raw/networking/ftpd.c
    ${BUSYBOX_PATH}/raw/networking/httpd.c
    ${BUSYBOX_PATH}/raw/networking/nc.c
    ${BUSYBOX_PATH}/raw/networking/ntpd.c
    ${BUSYBOX_PATH}/raw/networking/parse_pasv_epsv.c
    ${BUSYBOX_PATH}/raw/networking/ping.c
    ${BUSYBOX_PATH}/raw/networking/telnet.c
    ${BUSYBOX_PATH}/raw/networking/telnetd.c
    ${BUSYBOX_PATH}/raw/networking/tftp.c
    ${BUSYBOX_PATH}/raw/networking/tls.c
    ${BUSYBOX_PATH}/raw/networking/tls_aes.c
    ${BUSYBOX_PATH}/raw/networking/tls_aesgcm.c
    ${BUSYBOX_PATH}/raw/networking/tls_fe.c
    ${BUSYBOX_PATH}/raw/networking/tls_pstm.c
    ${BUSYBOX_PATH}/raw/networking/tls_pstm_montgomery_reduce.c
    ${BUSYBOX_PATH}/raw/networking/tls_pstm_mul_comba.c
    ${BUSYBOX_PATH}/raw/networking/tls_pstm_sqr_comba.c
    ${BUSYBOX_PATH}/raw/networking/tls_rsa.c
    ${BUSYBOX_PATH}/raw/networking/tls_sp_c32.c
    ${BUSYBOX_PATH}/raw/networking/ssl_client.c
    ${BUSYBOX_PATH}/raw/networking/wget.c

    ${BUSYBOX_PATH}/raw/miscutils/ascii.c
    ${BUSYBOX_PATH}/raw/miscutils/bc.c
    ${BUSYBOX_PATH}/raw/miscutils/chat.c
    ${BUSYBOX_PATH}/raw/miscutils/devmem.c
    ${BUSYBOX_PATH}/raw/miscutils/fbsplash.c
    ${BUSYBOX_PATH}/raw/miscutils/hexedit.c
    ${BUSYBOX_PATH}/raw/miscutils/i2c_tools.c
    ${BUSYBOX_PATH}/raw/miscutils/less.c
    ${BUSYBOX_PATH}/raw/miscutils/lsscsi.c
    ${BUSYBOX_PATH}/raw/miscutils/man.c
    ${BUSYBOX_PATH}/raw/miscutils/microcom.c
    ${BUSYBOX_PATH}/raw/miscutils/partprobe.c
    ${BUSYBOX_PATH}/raw/miscutils/rx.c
    ${BUSYBOX_PATH}/raw/miscutils/setserial.c
    ${BUSYBOX_PATH}/raw/miscutils/strings.c
    ${BUSYBOX_PATH}/raw/miscutils/tree.c
    ${BUSYBOX_PATH}/raw/miscutils/ts.c
    ${BUSYBOX_PATH}/raw/miscutils/ttysize.c
    ${BUSYBOX_PATH}/raw/miscutils/volname.c

    ${BUSYBOX_PATH}/raw/procps/free.c

    ${BUSYBOX_PATH}/raw/shell/cttyhack.c
    ${BUSYBOX_PATH}/raw/shell/hush.c
    ${BUSYBOX_PATH}/raw/shell/match.c
    ${BUSYBOX_PATH}/raw/shell/math.c
    ${BUSYBOX_PATH}/raw/shell/random.c
    ${BUSYBOX_PATH}/raw/shell/shell_common.c

    ${BUSYBOX_PATH}/raw/util-linux/mkfs_vfat.c

    ${BUSYBOX_PATH}/raw/libbb/appletlib.c
    ${BUSYBOX_PATH}/raw/libbb/ask_confirmation.c
    ${BUSYBOX_PATH}/raw/libbb/auto_string.c
    ${BUSYBOX_PATH}/raw/libbb/bb_askpass.c
    ${BUSYBOX_PATH}/raw/libbb/bb_bswap_64.c
    ${BUSYBOX_PATH}/raw/libbb/bb_cat.c
    ${BUSYBOX_PATH}/raw/libbb/bb_do_delay.c
    ${BUSYBOX_PATH}/raw/libbb/bb_getgroups.c
    ${BUSYBOX_PATH}/raw/libbb/bb_getsockname.c
    ${BUSYBOX_PATH}/raw/libbb/bb_pwd.c
    ${BUSYBOX_PATH}/raw/libbb/bb_qsort.c
    ${BUSYBOX_PATH}/raw/libbb/bb_strtod.c
    ${BUSYBOX_PATH}/raw/libbb/bb_strtonum.c
    ${BUSYBOX_PATH}/raw/libbb/bbunit.c
    ${BUSYBOX_PATH}/raw/libbb/change_identity.c
    ${BUSYBOX_PATH}/raw/libbb/chomp.c
    ${BUSYBOX_PATH}/raw/libbb/common_bufsiz.c
    ${BUSYBOX_PATH}/raw/libbb/compare_string_array.c
    ${BUSYBOX_PATH}/raw/libbb/concat_path_file.c
    ${BUSYBOX_PATH}/raw/libbb/concat_subpath_file.c
    ${BUSYBOX_PATH}/raw/libbb/const_hack.c
    ${BUSYBOX_PATH}/raw/libbb/copy_file.c
    ${BUSYBOX_PATH}/raw/libbb/copyfd.c
    ${BUSYBOX_PATH}/raw/libbb/correct_password.c
    ${BUSYBOX_PATH}/raw/libbb/crc32.c
    ${BUSYBOX_PATH}/raw/libbb/default_error_retval.c
    ${BUSYBOX_PATH}/raw/libbb/device_open.c
    ${BUSYBOX_PATH}/raw/libbb/dump.c
    ${BUSYBOX_PATH}/raw/libbb/duration.c
    ${BUSYBOX_PATH}/raw/libbb/endofname.c
    ${BUSYBOX_PATH}/raw/libbb/executable.c
    ${BUSYBOX_PATH}/raw/libbb/fclose_nonstdin.c
    ${BUSYBOX_PATH}/raw/libbb/fflush_stdout_and_exit.c
    ${BUSYBOX_PATH}/raw/libbb/fgets_str.c
    ${BUSYBOX_PATH}/raw/libbb/find_mount_point.c
    ${BUSYBOX_PATH}/raw/libbb/find_pid_by_name.c
    ${BUSYBOX_PATH}/raw/libbb/find_root_device.c
    ${BUSYBOX_PATH}/raw/libbb/full_write.c
    ${BUSYBOX_PATH}/raw/libbb/get_console.c
    ${BUSYBOX_PATH}/raw/libbb/get_cpu_count.c
    ${BUSYBOX_PATH}/raw/libbb/get_last_path_component.c
    ${BUSYBOX_PATH}/raw/libbb/get_line_from_file.c
    ${BUSYBOX_PATH}/raw/libbb/get_shell_name.c
    ${BUSYBOX_PATH}/raw/libbb/get_volsize.c
    ${BUSYBOX_PATH}/raw/libbb/getopt_allopts.c
    ${BUSYBOX_PATH}/raw/libbb/getopt32.c
    ${BUSYBOX_PATH}/raw/libbb/getpty.c
    ${BUSYBOX_PATH}/raw/libbb/hash_md5_sha.c
    ${BUSYBOX_PATH}/raw/libbb/herror_msg.c
    ${BUSYBOX_PATH}/raw/libbb/human_readable.c
    ${BUSYBOX_PATH}/raw/libbb/in_ether.c
    ${BUSYBOX_PATH}/raw/libbb/inet_cksum.c
    ${BUSYBOX_PATH}/raw/libbb/inet_common.c
    ${BUSYBOX_PATH}/raw/libbb/inode_hash.c
    ${BUSYBOX_PATH}/raw/libbb/isdirectory.c
    ${BUSYBOX_PATH}/raw/libbb/isqrt.c
    ${BUSYBOX_PATH}/raw/libbb/iterate_on_dir.c
    ${BUSYBOX_PATH}/raw/libbb/kernel_version.c
    ${BUSYBOX_PATH}/raw/libbb/last_char_is.c
    ${BUSYBOX_PATH}/raw/libbb/lineedit.c
    ${BUSYBOX_PATH}/raw/libbb/lineedit_ptr_hack.c
    ${BUSYBOX_PATH}/raw/libbb/llist.c
    ${BUSYBOX_PATH}/raw/libbb/logenv.c
    ${BUSYBOX_PATH}/raw/libbb/login.c
    ${BUSYBOX_PATH}/raw/libbb/loop.c
    ${BUSYBOX_PATH}/raw/libbb/make_directory.c
    ${BUSYBOX_PATH}/raw/libbb/makedev.c
    ${BUSYBOX_PATH}/raw/libbb/match_fstype.c
    ${BUSYBOX_PATH}/raw/libbb/messages.c
    ${BUSYBOX_PATH}/raw/libbb/missing_syscalls.c
    ${BUSYBOX_PATH}/raw/libbb/mode_string.c
    ${BUSYBOX_PATH}/raw/libbb/mtab.c
    ${BUSYBOX_PATH}/raw/libbb/nuke_str.c
    ${BUSYBOX_PATH}/raw/libbb/obscure.c
    ${BUSYBOX_PATH}/raw/libbb/parse_config.c
    ${BUSYBOX_PATH}/raw/libbb/parse_mode.c
    ${BUSYBOX_PATH}/raw/libbb/percent_decode.c
    ${BUSYBOX_PATH}/raw/libbb/perror_msg.c
    ${BUSYBOX_PATH}/raw/libbb/perror_nomsg.c
    ${BUSYBOX_PATH}/raw/libbb/perror_nomsg_and_die.c
    ${BUSYBOX_PATH}/raw/libbb/pidfile.c
    ${BUSYBOX_PATH}/raw/libbb/platform.c
    ${BUSYBOX_PATH}/raw/libbb/print_flags.c
    ${BUSYBOX_PATH}/raw/libbb/print_numbered_lines.c
    ${BUSYBOX_PATH}/raw/libbb/printable.c
    ${BUSYBOX_PATH}/raw/libbb/printable_string.c
    ${BUSYBOX_PATH}/raw/libbb/process_escape_sequence.c
    ${BUSYBOX_PATH}/raw/libbb/procps.c
    ${BUSYBOX_PATH}/raw/libbb/progress.c
    ${BUSYBOX_PATH}/raw/libbb/ptr_to_globals.c
    ${BUSYBOX_PATH}/raw/libbb/pw_encrypt.c
    ${BUSYBOX_PATH}/raw/libbb/read.c
    ${BUSYBOX_PATH}/raw/libbb/read_key.c
    ${BUSYBOX_PATH}/raw/libbb/read_printf.c
    ${BUSYBOX_PATH}/raw/libbb/recursive_action.c
    ${BUSYBOX_PATH}/raw/libbb/remove_file.c
    ${BUSYBOX_PATH}/raw/libbb/replace.c
    ${BUSYBOX_PATH}/raw/libbb/rtc.c
    ${BUSYBOX_PATH}/raw/libbb/run_shell.c
    ${BUSYBOX_PATH}/raw/libbb/safe_gethostname.c
    ${BUSYBOX_PATH}/raw/libbb/safe_poll.c
    ${BUSYBOX_PATH}/raw/libbb/safe_strncpy.c
    ${BUSYBOX_PATH}/raw/libbb/safe_write.c
    ${BUSYBOX_PATH}/raw/libbb/securetty.c
    ${BUSYBOX_PATH}/raw/libbb/setup_environment.c
    ${BUSYBOX_PATH}/raw/libbb/signals.c
    ${BUSYBOX_PATH}/raw/libbb/simplify_path.c
    ${BUSYBOX_PATH}/raw/libbb/single_argv.c
    ${BUSYBOX_PATH}/raw/libbb/skip_whitespace.c
    ${BUSYBOX_PATH}/raw/libbb/speed_table.c
    ${BUSYBOX_PATH}/raw/libbb/str_tolower.c
    ${BUSYBOX_PATH}/raw/libbb/strrstr.c
    ${BUSYBOX_PATH}/raw/libbb/sysconf.c
    ${BUSYBOX_PATH}/raw/libbb/time.c
    ${BUSYBOX_PATH}/raw/libbb/trim.c
    ${BUSYBOX_PATH}/raw/libbb/u_signal_names.c
    ${BUSYBOX_PATH}/raw/libbb/ubi.c
    ${BUSYBOX_PATH}/raw/libbb/udp_io.c
    ${BUSYBOX_PATH}/raw/libbb/update_passwd.c
    ${BUSYBOX_PATH}/raw/libbb/uuencode.c
    ${BUSYBOX_PATH}/raw/libbb/verror_msg.c
    ${BUSYBOX_PATH}/raw/libbb/vfork_daemon_rexec.c
    ${BUSYBOX_PATH}/raw/libbb/warn_ignoring_args.c
    ${BUSYBOX_PATH}/raw/libbb/wfopen.c
    ${BUSYBOX_PATH}/raw/libbb/wfopen_input.c
    ${BUSYBOX_PATH}/raw/libbb/write.c
    ${BUSYBOX_PATH}/raw/libbb/xatonum.c
    ${BUSYBOX_PATH}/raw/libbb/xconnect.c
    ${BUSYBOX_PATH}/raw/libbb/xfunc_die.c
    ${BUSYBOX_PATH}/raw/libbb/xfuncs.c
    ${BUSYBOX_PATH}/raw/libbb/xfuncs_printf.c
    ${BUSYBOX_PATH}/raw/libbb/xgetcwd.c
    ${BUSYBOX_PATH}/raw/libbb/zgethostbyname.c
    ${BUSYBOX_PATH}/raw/libbb/xreadlink.c
    ${BUSYBOX_PATH}/raw/libbb/xrealloc_vector.c
    ${BUSYBOX_PATH}/raw/libbb/xregcomp.c
)
vsf_add_compile_definitions(
    ${VSF_TARGET_DEFINITIONS}
    BB_VER=\"1.37.0.git\"
    ENABLE_USE_BB_CRYPT=1
    APP_USE_LINUX_BUSYBOX_DEMO=ENABLED
    __VSF__
    alloca=__builtin_alloca
)
vsf_add_include_directories(
    ${BUSYBOX_PATH}/port
    ${BUSYBOX_PATH}/raw
    ${BUSYBOX_PATH}/raw/include

    ${VSF_COMMON_INCLUDE_DIRECTORIES}
)
vsf_add_sources(
    ${BUSYBOX_SOURCES}
)

target_compile_options(${CMAKE_PROJECT_NAME} PUBLIC -include ${BUSYBOX_PATH}/port/autoconf.h)

if (NOT DEFINED VSF_APPLET)
    vsf_add_include_directories(
        ${BUSYBOX_PATH}/port/vsf_porting
    )
    vsf_add_sources(
        ${BUSYBOX_PATH}/port/vsf_porting/libbb_dynlib.c
    )
endif()