/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "takion.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(tkproto_TakionMessage, tkproto_TakionMessage, 2)


PB_BIND(tkproto_EventCode, tkproto_EventCode, AUTO)


PB_BIND(tkproto_BigPayload, tkproto_BigPayload, AUTO)


PB_BIND(tkproto_BangPayload, tkproto_BangPayload, AUTO)


PB_BIND(tkproto_InfoPayload, tkproto_InfoPayload, AUTO)


PB_BIND(tkproto_CursorPayload, tkproto_CursorPayload, AUTO)


PB_BIND(tkproto_TimerPayload, tkproto_TimerPayload, AUTO)


PB_BIND(tkproto_CorruptFramePayload, tkproto_CorruptFramePayload, AUTO)


PB_BIND(tkproto_PacketLossPayload, tkproto_PacketLossPayload, AUTO)


PB_BIND(tkproto_FpsChangePayload, tkproto_FpsChangePayload, AUTO)


PB_BIND(tkproto_DisconnectPayload, tkproto_DisconnectPayload, AUTO)


PB_BIND(tkproto_LogMessage, tkproto_LogMessage, AUTO)


PB_BIND(tkproto_LogPayload, tkproto_LogPayload, AUTO)


PB_BIND(tkproto_ClientMetric, tkproto_ClientMetric, AUTO)


PB_BIND(tkproto_ClientMetricPayload, tkproto_ClientMetricPayload, AUTO)


PB_BIND(tkproto_HeaderRequestPayload, tkproto_HeaderRequestPayload, AUTO)


PB_BIND(tkproto_DebugOption, tkproto_DebugOption, AUTO)


PB_BIND(tkproto_OverlayPayload, tkproto_OverlayPayload, AUTO)


PB_BIND(tkproto_BitratePayload, tkproto_BitratePayload, AUTO)


PB_BIND(tkproto_ResolutionPayload, tkproto_ResolutionPayload, AUTO)


PB_BIND(tkproto_AudioChannelPayload, tkproto_AudioChannelPayload, AUTO)


PB_BIND(tkproto_StreamInfoPayload, tkproto_StreamInfoPayload, AUTO)


PB_BIND(tkproto_XmbCommandPayload, tkproto_XmbCommandPayload, AUTO)


PB_BIND(tkproto_ConnectionQualityPayload, tkproto_ConnectionQualityPayload, AUTO)


PB_BIND(tkproto_PlayTimeLeftPayload, tkproto_PlayTimeLeftPayload, AUTO)


PB_BIND(tkproto_ServerMessagePayload, tkproto_ServerMessagePayload, AUTO)


PB_BIND(tkproto_ControllerConnectionPayload, tkproto_ControllerConnectionPayload, AUTO)


PB_BIND(tkproto_ClientInfoPayload, tkproto_ClientInfoPayload, AUTO)


PB_BIND(tkproto_VideoCapturePayload, tkproto_VideoCapturePayload, AUTO)


PB_BIND(tkproto_AudioCapturePayload, tkproto_AudioCapturePayload, AUTO)


PB_BIND(tkproto_ServerSettingsPayload, tkproto_ServerSettingsPayload, AUTO)


PB_BIND(tkproto_GkTracePayload, tkproto_GkTracePayload, AUTO)


PB_BIND(tkproto_PeriodicTimestampPayload, tkproto_PeriodicTimestampPayload, AUTO)


PB_BIND(tkproto_DeepLinkPayload, tkproto_DeepLinkPayload, AUTO)


PB_BIND(tkproto_MicInfoPayload, tkproto_MicInfoPayload, AUTO)


PB_BIND(tkproto_DirectMessagePayload, tkproto_DirectMessagePayload, AUTO)


PB_BIND(tkproto_MicConnectionPayload, tkproto_MicConnectionPayload, AUTO)


PB_BIND(tkproto_TakionProtocolRequestPayload, tkproto_TakionProtocolRequestPayload, AUTO)


PB_BIND(tkproto_TakionProtocolRequestAckPayload, tkproto_TakionProtocolRequestAckPayload, AUTO)


PB_BIND(tkproto_SenkushaPayload, tkproto_SenkushaPayload, AUTO)


PB_BIND(tkproto_SenkushaEchoCommand, tkproto_SenkushaEchoCommand, AUTO)


PB_BIND(tkproto_SenkushaMtuCommand, tkproto_SenkushaMtuCommand, AUTO)


PB_BIND(tkproto_SenkushaBandwidthCommand, tkproto_SenkushaBandwidthCommand, AUTO)


PB_BIND(tkproto_SenkushaClientMtuCommand, tkproto_SenkushaClientMtuCommand, AUTO)
















#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

